--- #YAML:1.0
name:                POE-Filter-Swank
version:             0.01
abstract:            Stream based filter for the Swank protocol
license:             perl
author:              
    - Ævar Arnfjörð Bjarmason <avar@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    POE:                           0.9999
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
